
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by editing the '
          'lib/firebase_options.dart file.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCANjdwwqHJTgWoinu2lrW6Bgeubd_533g',
    appId: '1:652222620401:android:PLACEHOLDER',
    messagingSenderId: '652222620401',
    projectId: 'taxiapp-88e0f',
    storageBucket: 'taxiapp-88e0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANjdwwqHJTgWoinu2lrW6Bgeubd_533g',
    appId: '1:652222620401:ios:PLACEHOLDER',
    messagingSenderId: '652222620401',
    projectId: 'taxiapp-88e0f',
    storageBucket: 'taxiapp-88e0f.firebasestorage.app',
    iosBundleId: 'com.taxinanban.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCANjdwwqHJTgWoinu2lrW6Bgeubd_533g',
    appId: '1:652222620401:ios:PLACEHOLDER',
    messagingSenderId: '652222620401',
    projectId: 'taxiapp-88e0f',
    storageBucket: 'taxiapp-88e0f.firebasestorage.app',
    iosBundleId: 'com.taxinanban.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCANjdwwqHJTgWoinu2lrW6Bgeubd_533g',
    appId: '1:652222620401:web:PLACEHOLDER',
    messagingSenderId: '652222620401',
    projectId: 'taxiapp-88e0f',
    authDomain: 'taxiapp-88e0f.firebaseapp.com',
    storageBucket: 'taxiapp-88e0f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCANjdwwqHJTgWoinu2lrW6Bgeubd_533g',
    appId: '1:652222620401:web:PLACEHOLDER',
    messagingSenderId: '652222620401',
    projectId: 'taxiapp-88e0f',
    authDomain: 'taxiapp-88e0f.firebaseapp.com',
    storageBucket: 'taxiapp-88e0f.firebasestorage.app',
  );
}
